## config for training
source: ../data/trial_nyu.csv  # training file
#test_source: ../data/trial_nyu.csv # val file
model_dir: ./model #path to save the model
vgg_path: ./VGG_ILSVRC_16_layers.npy


# training params
batch_size: 1  # batch_size
lr: 0.001
max_epoch: 100
snapshot: 2500
#test_iter: 100
#momentum: 0.9
#stepsize: 50
#gamma: 0.1
weight_decay: 0.001
invalid_label: 19
c: 1.02
num_classes: 3

# [width, height] shape
image_size: [224, 224]
label_size: [224, 224]
label_channel: 3  #the label map channel
mean: [0, 0, 0] # image mean to sub
display: 1
