## config for training
source: ../data/train_nyu.csv  # training file
test_source: ../data/val_nyu.csv # val file
model_dir: ./model_e #path to save the model
vgg_path: ./VGG_ILSVRC_16_layers.npy


# training params
batch_size: 4  # batch_size
test_batch: 4
lr: 0.001
max_epoch: 100
test_iter: 100
snapshot: 5000
mirror: True
#test_iter: 100
#momentum: 0.9
#stepsize: 50
#gamma: 0.1
weight_decay: 0.001
invalid_label: 0.0
num_classes: 3

# [width, height] shape
image_size: [256, 256]
label_size: [256, 256]
label_channel: 3  #the label map channel
mean: [0, 0, 0] # image mean to sub
display: 1
