## config for training
source: ../data/trial_nyu.csv  # training file
#test_source: ../data/val_cityscape.csv # val file
model_dir: ./nyu_model


# training params
batch_size: 10  # batch_size
#test_batch: 10
lr: 0.001
max_epoch: 800
test_iter: 50
#momentum: 0.9
#stepsize: 50
#gamma: 0.1
snapshot: 1000
weight_decay: 0 #0.002
train_decoder: True
invalid_label: 0.0
#c: 1.02
num_classes: 3

# [width, height] shape
image_size: [256, 256]
label_size: [256, 256]
label_channel: 3  #the label map channel
mean: [0, 0, 0] # image mean to sub
display: 1
