## config for training
source: ../data/train_nyu.csv  # training file
test_source: ../data/val_nyu.csv # val file
model_dir: ./nyu_model


# training params
batch_size: 8  # batch_size
test_batch: 8
lr: 0.001
max_epoch: 100
test_iter: 50
mirror: True
snapshot: 5000
weight_decay: 0.0002
train_decoder: True
invalid_label: 0.0
#c: 1.02
num_classes: 3

# [width, height] shape
image_size: [256, 256]
label_size: [256, 256]
label_channel: 3  #the label map channel
mean: [0, 0, 0] # image mean to sub
display: 5
